name: j-and-d-compose

services:
  boot:
    # build:
    # context: /workspace/SOPRA-250905-GIT/quest-boot
    # context: ./quest-boot

    image: ajc/j-and-d:boot
    container_name: j-and-d-boot

    environment:
      #VERIFIER SI CA MARCHE
      SPRING_DATASOURCE_URL: jdbc:mysql://20.199.40.49:3336/j_and_d
      #SPRING_DATASOURCE_PASSWORD: root

    networks:
      - j-and-d

  angular:
    image: ajc/j-and-d:angular
    container_name: j-and-d-angular

    ports:
      - 80:80

    depends_on:
      - boot

    networks:
      - j-and-d

networks:
  j-and-d:
    name: j-and-d
    external: true
